---
title: "Hospital mortality in a tertiary hospital in Ghana"
author: "Eric Anku"
format: html
---

```{r load-packages}
# Load packages
pacman::p_load(
  tidyverse, # Data wrangling and visualisation
  skimr, # Skim data
  gtsummary, # Table summary
  rio, # Import and export dataset
  here, # File management
  janitor, # Clean names
  finalfit, # Labelling
  ggstatsplot # Exploratory data analysis
)
```

```{r import-dataset}
# Import dataset
df <- import(here("data","mortality_data.xlsx"), skip = 5)
```


```{r clean-names}
# Clean column names
df <- clean_names(df)
```

```{r de-identify-dataset}
# Remove PII columns and redundant columns
df <- df |> 
  select(-c(
    patient_name,
    patient_number,
    mobile,
    address,
    emergency_contact,
    emergency_contact_name,
    mortuary_patient_tag,
    mortuary_out_date,
    mortuary_added_date,
    action
  ))
```

```{r skim-dataset}
# Skim dataset
df |>
  skim()
```

```{r glimpse-dataset}
# Glimpse dataset
df |>
  glimpse()
```



```{r data-wrangling}
# Data cleaning 
df <- df |> 
  mutate(
    # Extract years from age variable and convert to numeric data
    numeric_age = str_replace_all(age, "\\D", " ") |>
      # Label age variable
      ff_label("Age (years)"), 
    # Convert age into factor and label
    gender = fct(gender) |>
      ff_label("Sex"),
    # Convert occupation into factor and label
    occupation = fct(occupation) |>
      ff_label("Occupation"),
    # Convert education into factor and label
    education = fct(education) |>
      ff_label("Educational status"),
    # Convert deceased date into date and label
    deceased_date = dmy_hms(deceased_date) |>
      ff_label("Deceased date"),
    # Convert patient location into factor and label
    patient_death_location = fct(patient_death_location) |>
      ff_label("Death location"),
    # Convert date of admission into date and label
    date_of_admission = ymd(date_of_admission) |>
      ff_label("Date of admission"),
    # Convert numeric age to numeric
    numeric_age = as.integer(numeric_age)
  )
```

```{r glimpse-data-inspection}
# Inspect dataset
df |>
  glimpse()
```


```{r missing-data}
# Glimpse missing data
df |>
  missing_glimpse()
```

```{r remove-existing-age}
# Remove existing age variable
df <- df |>
  select(-age)
```

## Exploratory data analysis


```{r}
skim(df)
```

```{r histogram-age}
df |>
  gghistostats(numeric_age)
```
```{r barcharts-factor}
barcharts <- function(df, x) {
  df |>
  ggplot(aes(fct_infreq(x))) +
  geom_bar() +
  coord_flip()
}

# Bar chart for gender
barcharts(df, df$gender)

# Bar chart for occupation
barcharts(df, df$occupation)

# Bar chart for education
barcharts(df, df$education)

# Bar chart for patient date location
barcharts(df, df$patient_death_location)
```


```{r check-levels-occupation}
# OCcupation
levels(df$occupation)
```


```{r check-levels-education}
# Education
levels(df$education)
```

```{r check-levels-death-location}
# Patient death location
levels(df$patient_death_location)
```


```{r additional-cleaning}
# Factor recode occupation, education, patient date location
```

